//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.ÖDÜNÇ = new HashSet<ÖDÜNÇ>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<int> YAZAR { get; set; }
        public string YIL { get; set; }
        public string YAYINEVİ { get; set; }
        public string RESİM { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual Yazar Yazar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÖDÜNÇ> ÖDÜNÇ { get; set; }
    }
}
